default: &default
  endpoint: 'ec2.ap-northeast-1.amazonaws.com'
  email: 'johnwu@tripmement.com'
  domain: '52.196.11.89'

  # in Rails.root, path to private key
  private_key: 'key/keyfile.pem'

  # in Rails.root, path where certificates
  # will be stored (on Heroku this variable is ignored)
  output_cert_dir: 'certificates'

  # in Rails.root, path where challenge token
  # will be stored in case when DB will not be used
  challenge_dir_name: 'challenge'

production:
  <<: *default

staging:
  <<: *default

development:
  <<: *default

test:
  <<: *default